# Linear Algebra

In [1]:
import numpy as np

In [4]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [5]:
print("v1 + v2:", v1+v2)

v1 + v2: [5 7 9]


In [6]:
print(v1 * 2)

[2 4 6]


In [7]:
print(np.dot(v1, v2)) #1x4 + 2x5 + 3x6

32


In [9]:
print("Magnitude of  v1: ", np.linalg.norm(v1)) #The square root of the sum of the elements

Magnitude of  v1:  3.7416573867739413


In [15]:
A = np.array([[1, 2, 3], #2x3 matrix
              [4, 5, 6]])
print("Matrix A:\n", A)

Matrix A:
 [[1 2 3]
 [4 5 6]]


In [16]:
B = np.array([[1, 2, 3], #3x3 matrix
              [4, 5, 6],
              [7, 8, 9]])
print("Matrix B:\n", B)

Matrix B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
matrix_mul = np.dot(A, B) # A@B: dot product of the rows of the first matrix and the columns of the second matrix
print("A * B:\n", matrix_mul) 
#[[(1x1 + 2x4 + 3x7), (1x2 + 2x5 + 3x8), (...)]
#[(4x1 + 5x4 + 6x7), (...), (...)]]

A * B:
 [[30 36 42]
 [66 81 96]]


In [20]:
print("Transpose of A:\n", A.T) #Swaps rows and columns

Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]


A system of linear equations can be written in matrix form as:

Ax=b

Where:

● A is the coefficient matrix,

● x is the vector of unknowns,

● b is the constant vector.


In [21]:
#2x + 3y = 5
#4x - y = 3
# [[2, 3],     [[x]       [[5]
#  [4, -1]]     [y]]   =   [3]]

# Coefficient matrix A and constant vector b
A = np.array([[2, 3], [4, -1]])
b = np.array([5, 3])
# Solve the system A * x = b
x = np.linalg.solve(A, b)
print("Solution (x, y):", x)


Solution (x, y): [1. 1.]


Given a square matrix 𝐴, if there exists a scalar 𝜆 and a non-zero vector 𝑣 such that:

𝐴𝑣 = 𝜆𝑣

Then 𝜆 is an eigenvalue of 𝐴, and 𝑣 is the corresponding eigenvector.

Eigenvectors are directions that don’t change direction when a matrix acts on them.

Eigenvalues tell you how much those directions get stretched or squished.


In [22]:
A1 = np.array([[2, 1], [1, 2]])
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [ 4.27491722 -3.27491722]
Eigenvectors:
 [[ 0.79681209 -0.49436913]
 [ 0.60422718  0.86925207]]


In [25]:
A2 = np.array([[4, 7], [2, 6]])

A2_inv = np.linalg.inv(A2) # Compute the inverse of A
print("Inverse of A:\n", A2_inv)

identity = np.dot(A2, A2_inv) # Verify: A * A_inv should be the identity matrix
print("A * A_inv:\n", identity)
#Identity Matrix is just diagonal of 1s

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A * A_inv:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


Singular Value Decomposition (SVD) is a factorization of a matrix into three
matrices:

A = UΣV^T

U & V are orthogonal matrices

Σ is a diagonal matrix of singular values

In [27]:
A = np.array([[1, 2], [3, 4], [5, 6]])

U, sigma, Vt = np.linalg.svd(A)

print("U matrix:\n", U)
print("Sigma values:", sigma)
print("V^T matrix:\n", Vt)

U matrix:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma values: [9.52551809 0.51430058]
V^T matrix:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
