In [1]:
#Jacobi
import numpy as np
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    print(x)
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
        print(x)
        
    return x, max_iterations

In [2]:
#Gauss-Seidel
import numpy as np
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    print(x)
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
        print(x)
    return x, max_iterations

In [7]:
def diag_dominant(matrix):
    for i in range(len(matrix)):
        diagonal = abs(matrix[i][i])
        row_sum = sum(abs(matrix[i][j]) for j in range(len(matrix[i])) if j != i)

        if diagonal < row_sum:
            return False
    return True

In [11]:
A = np.array([[1, 0, 0, 0, 0],
            [0, 1, 0, 0, 0],
            [0, 0, 1, 0, 0],
            [0, 0, 0, 1, 0],
            [0, 0, 0, 0, 1]])

B = np.array([[0, 0, 1, 0, 0],
            [0, 1, 0, 1, 0],
            [0, 0, 1, 0, 10],
            [0, 0, 0, 1, 0],
            [10, 0, 0, 0, 1]])


print(diag_dominant(A))
print(A)

print(diag_dominant(B))
print(B)

    

True
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
False
[[ 0  0  1  0  0]
 [ 0  1  0  1  0]
 [ 0  0  1  0 10]
 [ 0  0  0  1  0]
 [10  0  0  0  1]]
